# Generated by Django 6.0 on 2025-12-18 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConditionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[("checkout", "Check-out"), ("checkin", "Check-in")], max_length=10
                    ),
                ),
                (
                    "fuel_level",
                    models.CharField(
                        choices=[
                            ("empty", "Empty"),
                            ("1/4", "1/4"),
                            ("1/2", "1/2"),
                            ("3/4", "3/4"),
                            ("full", "Full"),
                        ],
                        max_length=10,
                    ),
                ),
                ("mileage", models.PositiveIntegerField()),
                (
                    "exterior_condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("damaged", "Damaged"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "interior_condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("damaged", "Damaged"),
                        ],
                        max_length=20,
                    ),
                ),
                ("damages", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("inspector_name", models.CharField(blank=True, max_length=100)),
                ("customer_acknowledged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("contract_number", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_signature", "Pending Signature"),
                            ("signed", "Signed"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("terms_and_conditions", models.TextField(blank=True)),
                ("customer_signature", models.TextField(blank=True)),
                ("customer_signed_at", models.DateTimeField(blank=True, null=True)),
                ("staff_signature", models.TextField(blank=True)),
                ("staff_signed_at", models.DateTimeField(blank=True, null=True)),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to="contracts/")),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DamageComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("new_damages", models.JSONField(blank=True, default=list)),
                ("resolved_damages", models.JSONField(blank=True, default=list)),
                ("summary", models.TextField(blank=True)),
                ("total_new_damage_count", models.IntegerField(default=0)),
                (
                    "estimated_repair_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("error_message", models.TextField(blank=True)),
                ("model_used", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Damage comparisons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InspectionAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("damage_detection", "Damage Detection"),
                            ("dashboard_analysis", "Dashboard Analysis"),
                            ("comparison", "Comparison Analysis"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("model_used", models.CharField(blank=True, max_length=100)),
                ("processing_time_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Inspection analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConditionReportPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="condition_reports/")),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("front", "Front"),
                            ("back", "Back"),
                            ("driver_side", "Driver Side"),
                            ("passenger_side", "Passenger Side"),
                            ("interior_front", "Interior Front"),
                            ("interior_back", "Interior Back"),
                            ("dashboard", "Dashboard/Odometer"),
                            ("trunk", "Trunk"),
                            ("damage_detail", "Damage Detail"),
                            ("customer_submitted", "Customer Submitted"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "submitted_by",
                    models.CharField(
                        choices=[("staff", "Staff"), ("customer", "Customer")],
                        default="staff",
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "condition_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="contracts.conditionreport",
                    ),
                ),
            ],
            options={
                "ordering": ["location", "created_at"],
            },
        ),
    ]
