# Generated by Django 5.2.9 on 2025-12-17 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConditionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[("checkout", "Check-out"), ("checkin", "Check-in")], max_length=10
                    ),
                ),
                (
                    "fuel_level",
                    models.CharField(
                        choices=[
                            ("empty", "Empty"),
                            ("1/4", "1/4"),
                            ("1/2", "1/2"),
                            ("3/4", "3/4"),
                            ("full", "Full"),
                        ],
                        max_length=10,
                    ),
                ),
                ("mileage", models.PositiveIntegerField()),
                (
                    "exterior_condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("damaged", "Damaged"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "interior_condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("damaged", "Damaged"),
                        ],
                        max_length=20,
                    ),
                ),
                ("damages", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("inspector_name", models.CharField(blank=True, max_length=100)),
                ("customer_acknowledged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConditionReportPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="condition_reports/")),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("front", "Front"),
                            ("back", "Back"),
                            ("left", "Left Side"),
                            ("right", "Right Side"),
                            ("interior", "Interior"),
                            ("dashboard", "Dashboard"),
                            ("trunk", "Trunk"),
                            ("damage", "Damage Detail"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "condition_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="contracts.conditionreport",
                    ),
                ),
            ],
            options={
                "ordering": ["location", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("contract_number", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_signature", "Pending Signature"),
                            ("signed", "Signed"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("terms_and_conditions", models.TextField(blank=True)),
                ("customer_signature", models.TextField(blank=True)),
                ("customer_signed_at", models.DateTimeField(blank=True, null=True)),
                ("staff_signature", models.TextField(blank=True)),
                ("staff_signed_at", models.DateTimeField(blank=True, null=True)),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to="contracts/")),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("tenant", "contract_number")},
            },
        ),
        migrations.AddField(
            model_name="conditionreport",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="condition_reports",
                to="contracts.contract",
            ),
        ),
    ]
