# Generated by Django 6.0 on 2025-12-18 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conditionreportphoto",
            name="submitted_by",
            field=models.CharField(
                choices=[("staff", "Staff"), ("customer", "Customer")],
                default="staff",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="conditionreportphoto",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="conditionreportphoto",
            name="location",
            field=models.CharField(
                choices=[
                    ("front", "Front"),
                    ("back", "Back"),
                    ("driver_side", "Driver Side"),
                    ("passenger_side", "Passenger Side"),
                    ("interior_front", "Interior Front"),
                    ("interior_back", "Interior Back"),
                    ("dashboard", "Dashboard/Odometer"),
                    ("trunk", "Trunk"),
                    ("damage_detail", "Damage Detail"),
                    ("customer_submitted", "Customer Submitted"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DamageComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("new_damages", models.JSONField(blank=True, default=list)),
                ("resolved_damages", models.JSONField(blank=True, default=list)),
                ("summary", models.TextField(blank=True)),
                ("total_new_damage_count", models.IntegerField(default=0)),
                (
                    "estimated_repair_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("error_message", models.TextField(blank=True)),
                ("model_used", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "checkin_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_as_checkin",
                        to="contracts.conditionreport",
                    ),
                ),
                (
                    "checkout_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_as_checkout",
                        to="contracts.conditionreport",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Damage comparisons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InspectionAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("damage_detection", "Damage Detection"),
                            ("dashboard_analysis", "Dashboard Analysis"),
                            ("comparison", "Comparison Analysis"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("model_used", models.CharField(blank=True, max_length=100)),
                ("processing_time_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "condition_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="contracts.conditionreport",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="contracts.conditionreportphoto",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inspection analyses",
                "ordering": ["-created_at"],
            },
        ),
    ]
