# Generated by Django 6.0 on 2025-12-18 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0002_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="conditionreport",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="condition_reports",
                to="contracts.contract",
            ),
        ),
        migrations.AddField(
            model_name="damagecomparison",
            name="checkin_report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comparisons_as_checkin",
                to="contracts.conditionreport",
            ),
        ),
        migrations.AddField(
            model_name="damagecomparison",
            name="checkout_report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comparisons_as_checkout",
                to="contracts.conditionreport",
            ),
        ),
        migrations.AddField(
            model_name="inspectionanalysis",
            name="condition_report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="contracts.conditionreport",
            ),
        ),
        migrations.AddField(
            model_name="inspectionanalysis",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="contracts.conditionreportphoto",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contract",
            unique_together={("tenant", "contract_number")},
        ),
    ]
