# Generated by Django 6.0 on 2025-12-18 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, validators=[django.core.validators.EmailValidator()]
                    ),
                ),
                ("phone", models.CharField(max_length=30)),
                ("phone_secondary", models.CharField(blank=True, max_length=30)),
                (
                    "profile_photo",
                    models.ImageField(blank=True, null=True, upload_to="customer_photos/"),
                ),
                (
                    "profile_photo_source",
                    models.CharField(
                        blank=True,
                        choices=[("license", "From License"), ("upload", "Manual Upload")],
                        help_text="Source of the profile photo",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="USA", max_length=50)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("license_number", models.CharField(blank=True, max_length=50)),
                ("license_state", models.CharField(blank=True, max_length=50)),
                ("license_expiry", models.DateField(blank=True, null=True)),
                ("license_issue_date", models.DateField(blank=True, null=True)),
                (
                    "license_class",
                    models.CharField(
                        blank=True, help_text="License class (A, B, C, CDL, etc.)", max_length=20
                    ),
                ),
                (
                    "license_restrictions",
                    models.CharField(blank=True, help_text="License restrictions", max_length=200),
                ),
                (
                    "license_endorsements",
                    models.CharField(blank=True, help_text="License endorsements", max_length=200),
                ),
                (
                    "license_donor_status",
                    models.BooleanField(blank=True, help_text="Organ donor status", null=True),
                ),
                (
                    "license_image_front",
                    models.ImageField(blank=True, null=True, upload_to="customer_licenses/"),
                ),
                (
                    "license_image_back",
                    models.ImageField(blank=True, null=True, upload_to="customer_licenses/"),
                ),
                ("gender", models.CharField(blank=True, max_length=20)),
                (
                    "height",
                    models.CharField(
                        blank=True, help_text="Height (e.g., 5'10\" or 178cm)", max_length=20
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        blank=True, help_text="Weight (e.g., 180 lbs or 82kg)", max_length=20
                    ),
                ),
                ("eye_color", models.CharField(blank=True, max_length=30)),
                ("hair_color", models.CharField(blank=True, max_length=30)),
                ("license_ocr_parsed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "license_ocr_confidence",
                    models.FloatField(
                        blank=True, help_text="OCR confidence score (0.0-1.0)", null=True
                    ),
                ),
                ("is_blacklisted", models.BooleanField(default=False)),
                ("blacklist_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("license_front", "License Front"),
                            ("license_back", "License Back"),
                            ("passport", "Passport"),
                            ("id_card", "ID Card"),
                            ("insurance", "Insurance Card"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="customer_documents/")),
                ("description", models.CharField(blank=True, max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerInsurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("policy_number", models.CharField(max_length=100)),
                ("group_number", models.CharField(blank=True, max_length=100)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("policyholder_name", models.CharField(blank=True, max_length=200)),
                (
                    "policyholder_relationship",
                    models.CharField(
                        blank=True,
                        help_text="Relationship to customer (self, spouse, parent, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "coverage_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("liability", "Liability Only"),
                            ("collision", "Collision"),
                            ("comprehensive", "Comprehensive"),
                            ("full", "Full Coverage"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "covered_vehicles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of covered vehicles [{year, make, model, vin}]",
                    ),
                ),
                ("agent_name", models.CharField(blank=True, max_length=200)),
                ("agent_phone", models.CharField(blank=True, max_length=30)),
                (
                    "insurance_card_image",
                    models.ImageField(blank=True, null=True, upload_to="customer_insurance/"),
                ),
                ("ocr_parsed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ocr_confidence",
                    models.FloatField(
                        blank=True, help_text="OCR confidence score (0.0-1.0)", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Customer insurance records",
                "ordering": ["-created_at"],
            },
        ),
    ]
