# Generated by Django 6.0 on 2025-12-18 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("tenants", "0002_ocr_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="eye_color",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="customer",
            name="gender",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="customer",
            name="hair_color",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="customer",
            name="height",
            field=models.CharField(
                blank=True, help_text="Height (e.g., 5'10\" or 178cm)", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="license_class",
            field=models.CharField(
                blank=True, help_text="License class (A, B, C, CDL, etc.)", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="license_donor_status",
            field=models.BooleanField(blank=True, help_text="Organ donor status", null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="license_endorsements",
            field=models.CharField(blank=True, help_text="License endorsements", max_length=200),
        ),
        migrations.AddField(
            model_name="customer",
            name="license_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="license_ocr_confidence",
            field=models.FloatField(
                blank=True, help_text="OCR confidence score (0.0-1.0)", null=True
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="license_ocr_parsed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="license_restrictions",
            field=models.CharField(blank=True, help_text="License restrictions", max_length=200),
        ),
        migrations.AddField(
            model_name="customer",
            name="middle_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="customer",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="customer_photos/"),
        ),
        migrations.AddField(
            model_name="customer",
            name="profile_photo_source",
            field=models.CharField(
                blank=True,
                choices=[("license", "From License"), ("upload", "Manual Upload")],
                help_text="Source of the profile photo",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="weight",
            field=models.CharField(
                blank=True, help_text="Weight (e.g., 180 lbs or 82kg)", max_length=20
            ),
        ),
        migrations.CreateModel(
            name="CustomerInsurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("policy_number", models.CharField(max_length=100)),
                ("group_number", models.CharField(blank=True, max_length=100)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("policyholder_name", models.CharField(blank=True, max_length=200)),
                (
                    "policyholder_relationship",
                    models.CharField(
                        blank=True,
                        help_text="Relationship to customer (self, spouse, parent, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "coverage_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("liability", "Liability Only"),
                            ("collision", "Collision"),
                            ("comprehensive", "Comprehensive"),
                            ("full", "Full Coverage"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "covered_vehicles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of covered vehicles [{year, make, model, vin}]",
                    ),
                ),
                ("agent_name", models.CharField(blank=True, max_length=200)),
                ("agent_phone", models.CharField(blank=True, max_length=30)),
                (
                    "insurance_card_image",
                    models.ImageField(blank=True, null=True, upload_to="customer_insurance/"),
                ),
                ("ocr_parsed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ocr_confidence",
                    models.FloatField(
                        blank=True, help_text="OCR confidence score (0.0-1.0)", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_records",
                        to="customers.customer",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="insurance_records",
                        to="customers.customerdocument",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Customer insurance records",
                "ordering": ["-created_at"],
            },
        ),
    ]
