# Generated by Django 6.0 on 2025-12-18 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "require_email_verification",
                    models.BooleanField(
                        default=False, help_text="Require email verification for new user accounts"
                    ),
                ),
                (
                    "allow_custom_domains",
                    models.BooleanField(
                        default=True, help_text="Allow tenants to configure custom domains"
                    ),
                ),
                (
                    "allow_customer_registration",
                    models.BooleanField(
                        default=True, help_text="Allow customers to self-register on tenant sites"
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(
                        default="FleetFlow",
                        help_text="Name displayed in platform-level interfaces",
                        max_length=100,
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Enable maintenance mode (blocks all non-superuser access)",
                    ),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        blank=True,
                        default="We are currently performing scheduled maintenance. Please check back soon.",
                        help_text="Message shown during maintenance mode",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform Settings",
                "verbose_name_plural": "Platform Settings",
            },
        ),
        migrations.CreateModel(
            name="ImpersonationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Reason for impersonation (ticket number, support request, etc.)"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        help_text="The super admin who initiated the impersonation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonation_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        help_text="The user being impersonated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonated_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="The tenant context during impersonation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impersonation Log",
                "verbose_name_plural": "Impersonation Logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("tenant_create", "Tenant Created"),
                            ("tenant_update", "Tenant Updated"),
                            ("tenant_suspend", "Tenant Suspended"),
                            ("tenant_reactivate", "Tenant Reactivated"),
                            ("tenant_delete", "Tenant Deleted"),
                            ("user_create", "User Created"),
                            ("user_update", "User Updated"),
                            ("user_delete", "User Deleted"),
                            ("impersonate_start", "Impersonation Started"),
                            ("impersonate_end", "Impersonation Ended"),
                            ("settings_update", "Platform Settings Updated"),
                            ("plan_change", "Subscription Plan Changed"),
                            ("feature_toggle", "Feature Flag Toggled"),
                        ],
                        help_text="Type of action performed",
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Human-readable description of the action"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON object with before/after values for changes",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        help_text="The admin who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User affected by this action (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_actions_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant affected by this action (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Audit Log",
                "verbose_name_plural": "Platform Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
