# Generated by Django 6.0 on 2025-12-18 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantBranding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Primary brand color in hex format (e.g., #3B82F6)",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#1E40AF",
                        help_text="Secondary brand color in hex format",
                        max_length=7,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#10B981",
                        help_text="Accent color for highlights and CTAs",
                        max_length=7,
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#1F2937", help_text="Primary text color", max_length=7
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#FFFFFF",
                        help_text="Background color for main content area",
                        max_length=7,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Company logo (recommended: 200x50px PNG with transparency)",
                        null=True,
                        upload_to="tenant_branding/logos/",
                    ),
                ),
                (
                    "logo_dark",
                    models.ImageField(
                        blank=True,
                        help_text="Logo for dark backgrounds",
                        null=True,
                        upload_to="tenant_branding/logos/",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Favicon (recommended: 32x32px PNG or ICO)",
                        null=True,
                        upload_to="tenant_branding/favicons/",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Short tagline displayed on landing page",
                        max_length=200,
                    ),
                ),
                (
                    "welcome_message",
                    models.TextField(blank=True, help_text="Welcome message for landing page"),
                ),
                (
                    "show_powered_by",
                    models.BooleanField(
                        default=True, help_text='Show "Powered by FleetFlow" in footer'
                    ),
                ),
                (
                    "custom_css",
                    models.TextField(
                        blank=True, help_text="Custom CSS for advanced styling (use with caution)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branding",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Branding",
                "verbose_name_plural": "Tenant Branding",
            },
        ),
    ]
