# Generated by Django 6.0 on 2025-12-18 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("openrouter_api_key_encrypted", models.BinaryField(blank=True, null=True)),
                ("openrouter_enabled", models.BooleanField(default=False)),
                (
                    "openrouter_model",
                    models.CharField(
                        choices=[
                            ("anthropic/claude-3.5-sonnet", "Claude 3.5 Sonnet (Recommended)"),
                            ("anthropic/claude-3-opus", "Claude 3 Opus"),
                            ("openai/gpt-4-vision-preview", "GPT-4 Vision"),
                            ("google/gemini-pro-vision", "Gemini Pro Vision"),
                        ],
                        default="anthropic/claude-3.5-sonnet",
                        help_text="Vision model to use for OCR",
                        max_length=100,
                    ),
                ),
                (
                    "auto_parse_license",
                    models.BooleanField(
                        default=True, help_text="Automatically parse license images on upload"
                    ),
                ),
                (
                    "auto_parse_insurance",
                    models.BooleanField(
                        default=True, help_text="Automatically parse insurance documents on upload"
                    ),
                ),
                ("ocr_requests_today", models.IntegerField(default=0)),
                ("ocr_requests_reset_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Settings",
                "verbose_name_plural": "Tenant Settings",
            },
        ),
    ]
