# Generated by Django 6.0 on 2025-12-18 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenant_branding"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="Custom domain (e.g., rentals.mycompany.com)",
                        max_length=253,
                        unique=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, help_text="Primary domain for this tenant"),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("failed", "Verification Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(
                        blank=True, help_text="Token for DNS TXT record verification", max_length=64
                    ),
                ),
                (
                    "ssl_provisioned",
                    models.BooleanField(
                        default=False, help_text="Whether SSL certificate has been provisioned"
                    ),
                ),
                (
                    "ssl_expires_at",
                    models.DateTimeField(
                        blank=True, help_text="SSL certificate expiration date", null=True
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Domain",
                "verbose_name_plural": "Tenant Domains",
                "ordering": ["-is_primary", "domain"],
            },
        ),
    ]
