# Generated by Django 6.0 on 2025-12-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenant_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="rental_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=2.5,
                help_text="Per-rental fee charged to tenant (0 for Professional+)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="plan",
            field=models.CharField(
                choices=[
                    ("personal", "Personal"),
                    ("starter", "Starter"),
                    ("professional", "Professional"),
                    ("business", "Business"),
                    ("enterprise", "Enterprise"),
                ],
                default="personal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("trialing", "Trialing"),
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("canceled", "Canceled"),
                    ("unpaid", "Unpaid"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="vehicle_limit",
            field=models.IntegerField(default=3),
        ),
    ]
