# Generated by Django 5.2.9 on 2025-12-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeadCapture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "lead_type",
                    models.CharField(
                        choices=[("owner", "Has Cars to Rent"), ("renter", "Looking for Rental")],
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(default="homepage", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("converted", models.BooleanField(default=False)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferralCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("referrer_email", models.EmailField(max_length=254)),
                ("referred_email", models.EmailField(max_length=254)),
                (
                    "referral_type",
                    models.CharField(
                        choices=[("owner", "Has Cars to Rent"), ("renter", "Looking for Rental")],
                        max_length=20,
                    ),
                ),
                (
                    "credit_amount",
                    models.DecimalField(decimal_places=2, default=25.0, max_digits=6),
                ),
                ("referrer_credited", models.BooleanField(default=False)),
                ("referred_credited", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Referral Credit",
                "verbose_name_plural": "Referral Credits",
                "ordering": ["-created_at"],
            },
        ),
    ]
