from .license import LICENSE_OCR_SYSTEM_PROMPT, LICENSE_OCR_USER_PROMPT
from .insurance import INSURANCE_OCR_SYSTEM_PROMPT, INSURANCE_OCR_USER_PROMPT

__all__ = [
    'LICENSE_OCR_SYSTEM_PROMPT',
    'LICENSE_OCR_USER_PROMPT',
    'INSURANCE_OCR_SYSTEM_PROMPT',
    'INSURANCE_OCR_USER_PROMPT',
]
